### ISSUE TITLE
Unprocessable Entity when uploading track

### ISSUE THREAD

**Issue by Perpleex** [njasm/laravel5-soundcloud#10]
I have the same issue https://github.com/njasm/soundcloud/issues/19.

The solution was a mistake in branch 2.x and take the last version.

Composer file from laravel wrapper : 
  "minimum-stability": "dev",
  "require": {
    "njasm/soundcloud": "~2.0",

i think you need to update this to the last version.

**Comment by njasm** [comment]
hi @Perpleex 
did you run the following command already : `composer selfupdate && composer update njams/soundcloud` ?

the command didn't updated soundcloud package to the latest version ?

**Comment by Perpleex** [comment]
No they stay in previous version max 2.2.5.
I need to add directly soundcloud in my composer to have the lastest version.
