### ISSUE TITLE
undefined index: soundcloud

### ISSUE THREAD

**Issue by claudialexa** [njasm/laravel5-soundcloud#11]
When I try to publish the config settings, I'm getting this error:

  [ErrorException]  
  Undefined index: soundcloud 

any ideas?

**Comment by claudialexa** [comment]
Sorry, was able to fix this by editing services.php

**Comment by njasm** [comment]
cool @claudialexa glad you sort it out..

**Comment by selfpaidinc** [comment]
care to share what you edited inside services.php to fix?

**Comment by mandix** [comment]
Add this code from SoundCloud Credentials in config/services.php. Good luck!

'soundcloud' => [
    'client_id' => env('SOUNDCLOUD_CLIENT_ID'),
    'client_secret' => env('SOUNDCLOUD_CLIENT_SECRET'),
    'callback_url' => env('SOUNDCLOUD_CALLBACK_URL'),
],
