### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by tylergets** [njasm/laravel5-soundcloud#13]
What is needed to support 5.4? I'm willing to work on it if it's not already underway.

**Comment by njasm** [comment]
we just need to test the code on 5.4
checkout the repo,  and add it to a laravel 5.4 project and test it. 
everything should work as expected but didn't had the time to test it myself :(

**Comment by njasm** [comment]
keep me posted on your findings about your findings and tests

thanks for the help..
