### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by jessejamesrich** [njasm/laravel5-soundcloud#15]
Forgive me, I'm back to Laravel after a few years. What am I doing wrong here? I've edited composer.js as required. 

Could not find package laravel5-soundcloud at any version for your minimum-  
  stability (dev). Check the package spelling or your minimum-stability

**Comment by njasm** [comment]
@jessejamesrich I can't help you like that. it pretty much depends on your composer.json, laravel version ,etc.

What version of laravel you're using?
can you paste here your composer.json content?

did you 
```bash 
composer require njasm/laravel5-soundcloud
```
? If so, what's the error?

**Comment by jessejamesrich** [comment]
Sorry - I should have included the error. I just figure I was an idiot. 

`[InvalidArgumentException]                                                   
  Could not find package njasm/laravel5-soundcloud at any version for your mi  
  nimum-stability (stable). Check the package spelling or your minimum-stabil  
  ity`

PHP 7.0.20 MySQL 8.0.11.

![image](https://user-images.githubusercontent.com/13437954/40883057-5f04683a-66a9-11e8-80f0-d2e82a8117db.png)

**Comment by jessejamesrich** [comment]
Arg... now it works. Nothing changed TMK, but alas, apparently I am an idiot.

**Comment by njasm** [comment]
lol, @jessejamesrich calm down mate, You don't be so harsh on yourself ;)
It happens sometimes, a typo or so. Either way I'm glad you sort it all out and everything is working as expected!

have fun!
